steps:
# Bring in dependencies
- name: 'composer'
  args: ['global', 'require', 'hirak/prestissimo']
- name: 'composer'
  args: ['install']

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '--rm=false' , '-t', 'eu.gcr.io/$PROJECT_ID/legacy:latest', '.' ]

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/legacy:latest']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'legacy', '--image', 'eu.gcr.io/$PROJECT_ID/legacy:latest', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']
images:
       - 'eu.gcr.io/$PROJECT_ID/legacy:latest'
